name: py39
channels:
  - conda-forge
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.4.0=h27087fc_1
  - blas=1.0=mkl
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - cpython=3.9.23=py39hd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - ffmpeg=4.4.2=gpl_h45a1190_107
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.14.1=ha770c72_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py39h7196dd7_0
  - gnutls=3.7.6=he274497_3
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb03c661_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.9.82=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtasn1=4.20.0=hb03c661_1
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h2cb61b6_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=3.0.2=py39h9399b63_1
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nettle=3.8.1=hc379101_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=2.0.2=py39h9cb892a_1
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.3.0=h27087fc_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.5.4=h26f9b46_0
  - pillow=9.4.0=py39h2320bf1_1
  - pip=25.2=pyh8b19718_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.23=hc30ae73_0_cpython
  - python_abi=3.9=8_cp39
  - pytorch=2.5.1=py3.9_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.2=py39h9399b63_2
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - svt-av1=1.2.0=h27087fc_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchaudio=2.5.1=py39_cu124
  - torchtriton=3.1.0=py39
  - torchvision=0.20.1=py39_cu124
  - typing_extensions=4.14.1=pyhe01879c_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - click==8.1.8
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - grpcio==1.76.0
      - importlib-metadata==8.7.0
      - markdown==3.9
      - packaging==25.0
      - pandas==2.3.3
      - protobuf==6.33.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - regex==2025.9.18
      - scipy==1.13.1
      - six==1.17.0
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tqdm==4.67.1
      - tzdata==2025.2
      - wcwidth==0.2.14
      - werkzeug==3.1.3
      - zipp==3.23.0
prefix: /home/szp/miniconda3/envs/py39
